steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['package']
#- name: 'gcr.io/cloud-builders/docker'
#  args: ['build', '--tag=gcr.io/$PROJECT_ID/spring-boot', '.']
#images: ['gcr.io/$PROJECT_ID/spring-boot']
#steps:
- name: 'ubuntu'
  args: ['sh', '-c', 'pwd;ls -arl;']
- name: gcr.io/cloud-builders/docker
  entrypoint: '/bin/sh'
  args: ['-c', 'pwd; ls -arl; cd /workspace; pwd; ls -arl; cd /; ls -alr;']
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/skcchysk/github.com/salteeed/intensive_course', '.']
  dir:  '/workspace'
images: ['gcr.io/skcchysk/github.com/salteeed/intensive_course']