spring:
  application: 
    name: account-service 
  
  profiles:
    active: 
    - default
  
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
                
  datasource:
    url: jdbc:h2:mem:account
    driverClassName: org.h2.Driver
    username: sa
    password:
    
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: https://dining-eureka-pjmxazipaa-uc.a.run.app/eureka/
    enabled: true
  instance:
    preferIpAddress: true

zuul:  
  # service will be mapped under /api uri  
  prefix: /api  
  routes: 
    stock-service:  
      path: /account-service/**  
      url: http://dining-account-pjmxazipaa-uc.a.run.app
    
